### ISSUE TITLE
Stackage release?

### ISSUE THREAD

**Issue by sergv** [brandonchinn178/toml-reader#22]
For some users it would be useful to have this package on stackage in order to be able to use it as part of a snapshot. I can add it to stackage if you don't want to bother, just asking before doing anything.

**Comment by brandonchinn178** [comment]
It is 😄 
https://www.stackage.org/nightly-2022-09-28/package/toml-reader-0.1.0.0

I'm not sure why it's not in lts-19 though. I'll take a look
