### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by willbasky** [brandonchinn178/toml-reader#25]
> you could use [tomland](https://github.com/kowainik/tomland).

I am afraid it is outdated. It supports `0.5.0` version whereas current toml specification is `1.0.0` where is heterogeneous arrays for example.

**Comment by brandonchinn178** [comment]
Yes, I know. The whole reason I made this project is because tomland doesnt support v1. But if you need to write TOML files and you dont need v1 support, tomland is still an option

**Comment by willbasky** [comment]
Unfortunately I looked for v1 support.

**Comment by brandonchinn178** [comment]
I'm not sure what you're asking. What exactly are you looking for?

**Comment by willbasky** [comment]
For support of heterogeneous arrays.

Btw, I opened the issue for you to add details that tomland supports v0.5 only and to warn readers of the README wasting their times with tomland when they want features from v1 as I did.

**Comment by brandonchinn178** [comment]
toml-reader has support for heterogeneous arrays. Why were you looking at tomland? I'm not sure why the README for toml-reader should talk about what tomland supports.

Can you walk me through exactly what you did? What made you start looking at toml-reader? What made you decide toml-reader didnt work, and made you start looking at tomland?
