### ISSUE TITLE
Consider exposing DecoderM

### ISSUE THREAD

**Issue by berberman** [brandonchinn178/toml-reader#28]
That would be useful to run a decoder and get the result on `Value` instead of `Text`, as well as allow users to define their primitive decoder functions like [`getFieldsOptWith`](https://hackage.haskell.org/package/toml-reader-0.2.1.0/docs/src/TOML.Decode.html#getFieldsOptWith).

**Comment by brandonchinn178** [comment]
DecodeM _is_ exposed?

https://hackage.haskell.org/package/toml-reader-0.2.1.0/docs/TOML-Decode.html#t:DecodeM

**Comment by berberman** [comment]
Oh I missed that, thank you for your information.
